### ISSUE TITLE
Fail to launch neovide 0.12.1

### ISSUE THREAD

**Issue by corintho** [alex35mil/NeoHub#5]
With the latest release from neovide, the "--nofork" option became "--no-fork" and now it fails to launch

**Comment by bassamsdata** [comment]
I have the same issue, I run `neohub` with no arguments, and then I get a message complaining about `nofork`
<img width="401" alt="Screenshot 2024-01-16 at 1 01 39 PM" src="https://github.com/alex35mil/NeoHub/assets/105807570/978c8f51-683f-48bf-9eda-9a258a5fe1cf">

**Comment by dmartzol** [comment]
Same issue here

**Comment by corintho** [comment]
So, I went along and cloned the project locally.
We just need to change line 91 in the EditorStore file with the correct value for the flag: "--no-fork"
When you try to build it, it will complain about signing. Replace the signing team with your personal team and you should be all set. I am using the newly generated NeoHub app and it is working as expected.
Although I cannot distribute it to other people (I think)

**Comment by bassamsdata** [comment]
Hi @corintho,

Thank you for the solution. I actually forked the repo a few days ago and attempted the same process and was going to make a PR, but I encountered issues with building it related to signing (as I'm not familiar with Swift or Xcode). Xcode prevented me from obtaining the dmg file because it wasn't signed. Would you mind sharing the signing options you used?

Here is what I have:

<img width="867" alt="Screenshot 2024-02-13 at 11 22 25 AM" src="https://github.com/alex35mil/NeoHub/assets/105807570/000f42ef-01ec-4f6c-8253-e49e9cec0751">

Thank you!

**Comment by bassamsdata** [comment]
thanks, I started the project again and added my own account and now it's working. thank you

**Comment by alex35mil** [comment]
Sorry for the delay, folks. Should be fixed in the next release (after we merge #8).

**Comment by alex35mil** [comment]
It should be fixed in [`0.2.1`](https://github.com/alex35mil/NeoHub/releases/tag/v0.2.1`), but please see #15.

**Comment by alex35mil** [comment]
FYI I just updated `neovim` to the latest stable and `neovide` to the latest master (`0.13.1`) and things work again with `neohub@0.2.1`.
